name: calling_card_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.50.2=hf8de324_2
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.5.1=h81ee809_0
  - pip=25.1=pyhc872135_2
  - python=3.12.10=hc22306f_0_cpython
  - readline=8.2=h1a28f6b_0
  - setuptools=78.1.1=py312hca03da5_0
  - tk=8.6.13=h892fb3f_2
  - wheel=0.45.1=py312hca03da5_0
  - pip:
      - anndata==0.11.4
      - appdirs==1.4.4
      - array-api-compat==1.12.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.58.5
      - future==1.0.0
      - h5py==3.14.0
      - idna==3.10
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - legacy-api-wrap==1.4.1
      - liftover==1.3.2
      - llvmlite==0.44.0
      - matplotlib==3.10.3
      - mudata==0.3.2
      - natsort==8.4.0
      - networkx==3.5
      - numba==0.61.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.1
      - patsy==1.0.1
      - pillow==11.3.0
      - polars==1.31.0
      - pybedtools==0.12.0
      - pybigwig==0.3.24
      - pybktree==1.1
      - pycallingcards==1.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pysam==0.23.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2024.11.6
      - requests==2.28.2
      - scanpy==1.11.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - session-info2==0.1.2
      - six==1.17.0
      - statsmodels==0.14.5
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - umi-tools==1.1.6
      - urllib3==1.26.20
prefix: /Users/rileymullins/miniforge3/envs/calling_card_env
