name: paint_seq
channels:
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - liblzma=5.8.1
  - libopenssl-static=3.5.2
  - libpng=1.6.50
  - libuuid=2.38.1
  - libzlib=1.3.1
  - openssl=3.5.2
  - ucsc-bedgraphtobigwig=482
prefix: /Users/rileymullins/miniforge3/envs/paint_seq
